apiVersion: apps/v1
kind: Deployment
metadata:
  name: gonic
  namespace: gonic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gonic
  template:
    metadata:
      labels:
        app: gonic
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      initContainers:
      - name: init-dirs
        image: busybox:1.28
        command: ['sh', '-c', 'mkdir -p /var/lib/gonic/playlists && chmod -R 777 /var/lib/gonic']
        securityContext:
          runAsUser: 0  # Run as root to ensure permissions can be set
        volumeMounts:
        - name: gonic-data
          mountPath: /var/lib/gonic
      containers:
      - name: gonic
        image: sentriz/gonic:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: music
          mountPath: /music
          readOnly: true
        - name: gonic-data
          mountPath: /var/lib/gonic
        env:
        - name: GONIC_MUSIC_FOLDER
          value: /music
        - name: GONIC_LISTEN_ADDR
          value: ":8080"
        - name: GONIC_PLAYLISTS_DIR
          value: "/var/lib/gonic/playlists"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: music
        emptyDir: {}
      - name: gonic-data
        emptyDir: {}